# Generated by Django 6.0.1 on 2026-03-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=200)),
                ('github_link', models.URLField()),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
